// Generated stub - full proto client code would be generated by protoc
package search

import (
	context "context"
	grpc "google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

type SearchServiceClient interface {
	SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*SearchMessagesResponse, error)
	IndexMessage(ctx context.Context, in *IndexMessageRequest, opts ...grpc.CallOption) (*IndexMessageResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*SearchMessagesResponse, error) {
	out := new(SearchMessagesResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/SearchMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexMessage(ctx context.Context, in *IndexMessageRequest, opts ...grpc.CallOption) (*IndexMessageResponse, error) {
	out := new(IndexMessageResponse)
	err := c.cc.Invoke(ctx, "/search.SearchService/IndexMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
