// Code generated by protoc. DO NOT EDIT.
// Simplified version - full code would be generated
package search

type SearchMessagesRequest struct {
	Query    string
	ChannelId string
	GuildId  string
	AuthorId string
	Limit    int32
	Offset   int32
}

type SearchResult struct {
	MessageId uint64
	Content   string
	AuthorId  uint64
	ChannelId string
	Score     float32
	CreatedAt string
}

type SearchMessagesResponse struct {
	Results   []SearchResult
	TotalHits int64
}

type IndexMessageRequest struct {
	MessageId uint64
	Content   string
	AuthorId  uint64
	ChannelId string
	GuildId   string
	CreatedAt string
}

type IndexMessageResponse struct {
	Success bool
}
