// Generated stub - full proto client code would be generated by protoc
package audit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

type AuditServiceClient interface {
	LogEvent(ctx context.Context, in *LogEventRequest, opts ...grpc.CallOption) (*LogEventResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error)
	BatchLogEvents(ctx context.Context, in *BatchLogEventsRequest, opts ...grpc.CallOption) (*BatchLogEventsResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) LogEvent(ctx context.Context, in *LogEventRequest, opts ...grpc.CallOption) (*LogEventResponse, error) {
	out := new(LogEventResponse)
	err := c.cc.Invoke(ctx, "/audit.AuditService/LogEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsResponse, error) {
	out := new(GetLogsResponse)
	err := c.cc.Invoke(ctx, "/audit.AuditService/GetLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) BatchLogEvents(ctx context.Context, in *BatchLogEventsRequest, opts ...grpc.CallOption) (*BatchLogEventsResponse, error) {
	out := new(BatchLogEventsResponse)
	err := c.cc.Invoke(ctx, "/audit.AuditService/BatchLogEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
