// Code generated by protoc. DO NOT EDIT.
// Simplified version - full code would be generated
package audit

import "time"

type LogEventRequest struct {
	UserId    uint64
	Action    string
	TargetType string
	TargetId  string
	Scope     string
	Details   string
	IpAddress string
	UserAgent string
}

type LogEventResponse struct {
	Success bool
	Id      uint64
}

type GetLogsRequest struct {
	Page   int32
	Limit  int32
	UserId uint64
	Action string
}

type AuditLogEntry struct {
	Id         uint64
	UserId     uint64
	Action     string
	TargetType string
	TargetId   string
	Scope      string
	Details    string
	IpAddress  string
	CreatedAt  time.Time
}

type GetLogsResponse struct {
	Logs  []AuditLogEntry
	Total int64
}

type BatchLogEventsRequest struct {
	Events []LogEventRequest
}

type BatchLogEventsResponse struct {
	Count int32
}
